# Production Docker Compose configuration
# Use this for production deployment with SSL and additional security

version: '3.3'

services:
  app:
    build: .
    container_name: jewelry_store_app_prod
    restart: always
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - PORT=8000
      - DEBUG=False
    volumes:
      - ./price.xlsx:/app/price.xlsx:ro
      - ./static:/app/static:ro
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"



